
name: pip_clients_beacons_dart
version: 1.0.0
author: Sergey Seroukhov <seroukhov@gmail.com>
description: This is the sample Data microservice.
homepage: https://github.com/pip-services-samples/pip-clients-beacons-dart

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  pip_services3_commons: ">=1.0.5 <2.0.0"
  pip_services3_components: ">=1.0.2 <2.0.0"
  pip_services3_data: ">=1.0.0 <2.0.0"
  pip_services3_mongodb: ">=1.0.2 <2.0.0"
  pip_services3_rpc: ">=1.0.2 <2.0.0"
  pip_services3_container: ">=1.0.3 <2.0.0"
  http: "^0.12.0"
  angel_framework: ^2.1.1
  fixnum: ^0.10.11
  pip_services_beacons_dart:
    git:
      url: https://github.com/pip-services-samples/pip-services-beacons-dart

dev_dependencies:
  test: '>=1.14.2 <2.0.0'